### ISSUE TITLE
Research Web Frameworks

### ISSUE THREAD

**Issue by kiikoh** [DragonsOfTheEast/Ybox#42]

**Comment by JelaniJoseph** [comment]
When creating a branch, the name should be the framework or bootstrap that you are using. Please remember to also include a picture or code on how the frame would be implemented on the home screen and other pages

**Comment by kiikoh** [comment]
https://github.com/troxler/awesome-css-frameworks

**Comment by eisenjon16** [comment]
https://picturepan2.github.io/spectre/

**Comment by kiikoh** [comment]
UI Kit: https://getuikit.com/docs/introduction
Strengths: Actively Maintained, Comes with icon support, responsive
Weaknesses: Not easy to learn

**Comment by eisenjon16** [comment]
https://picturepan2.github.io/spectre/
Strengths:  - Provides basic styles for pure CSS components and utilities with best practice coding and consistent design language.  Gives good examples of using parts of the framework.

Weaknesses: Not the most popular one, doesn't seem very clear compared to other websites like Bootstrap.

**Comment by Harrison-Z1000** [comment]
**Bootstrap**
https://getbootstrap.com/
Strengths: Each component has great documentation, helps you avoid cross-browser bugs, helps you follow best practices in web design, holds more than 70% of the design framework market share
Weaknesses: Can require lots of CSS style overrides, website will look like many other sites out there without style customization, there is a learning curve for the classes and general workflow

Read more here: 
https://bootstrapcreative.com/pros-cons-using-bootstrap-web-development/

**Comment by JelaniJoseph** [comment]
Carbon Design System
https://www.carbondesignsystem.com/

Strengths: modular, and flexible easy to combine without much conflict. It also follows the learnable and memorable usability principles. Seems easy to understand has hyperlinks to see implementation methods 

Weaknesses:  has a lot of features so it's easy to get lost thinking about what to add, takes a while to learn how to use efficiently, requires a decent amount of resources to be downloaded or imported in order to use the product.

**Comment by ChristineCoan** [comment]
Semantic UI

Strengths: You can use the traditional code syntax you would usually use in non-framework environment. You can use it to build both simple (and truly complex) layouts. Also, you can use it for theming an existing layout to better reflect your design preferences and choices. It has a sleek, subtle, and flat design look that provides a lightweight user experience. There are elements that offer more customization. Easy to use, less time designing, and a wide variety of themes available.

Weaknesses: doesn’t support internet explorer 7. Smaller community, and few recent updates.
