### ISSUE TITLE
Usability Tests

### ISSUE THREAD

**Issue by kiikoh** [DragonsOfTheEast/Ybox#52]
Come up with tasks a user will commonly do on our website

**Comment by kiikoh** [comment]
Task 1: Visit the website and "add" a console to cart (The user just needs to click the button on the home page)

**Comment by JelaniJoseph** [comment]
Task 2: Visit the website and navigate to the About page, and locate the "view additional products page.

**Comment by ChristineCoan** [comment]
task 3: Visit the website navigate to the support page and check your account/profile

**Comment by Harrison-Z1000** [comment]
Task 4: Visit the website and enter your billing and payment details in the checkout form

**Comment by eisenjon16** [comment]
Task 5: Visit the website to the FAQ page and enter a question in the form
